#!/bin/bash

log_info () {
    red=`tput setaf 1`
    green=`tput setaf 2`
    yellow=`tput setaf 3`
    cyan=`tput setaf 6`
    reset=`tput sgr0`

    echo "${yellow}[3501-deploy] ${green}$1${reset}"
};

# rm old uberjar
log_info "removing old uberjar."
rm -rf ./target/uberjar

# create new uberjar
log_info "creating new uberjar..."
lein uberjar

# copy it over
log_info "copying uberjar to robot..."
scp ./target/uberjar/elisabet-*.jar lvuser@roboRIO-3501.local:/home/lvuser/FRCUserProgram.jar

log_info "excelsior!"
