#!/bin/bash

log_info () {
    red=`tput setaf 1`
    green=`tput setaf 2`
    yellow=`tput setaf 3`
    cyan=`tput setaf 6`
    reset=`tput sgr0`

    echo "${yellow}[3501-deploy] ${green}$1${reset}"
};

send_command () {
    ssh lvuser@roboRIO-3501.local $1
};

send_admin_command () {
    # do we need a password for this?
    ssh admin@roboRIO-3501.local $1
};

copy_file () {
    scp $1 lvuser@roboRIO-3501.local:$2
};

# rm old uberjar
log_info "removing old uberjar."
rm -rf ./target/uberjar

# create new uberjar
log_info "creating new uberjar..."
lein uberjar

# copy it over
log_info "copying uberjar to robot..."
copy_file ./target/uberjar/elisabet-*.jar /home/lvuser/FRCUserProgram.jar

# kill old code
log_info "killing old code..."

kill_netconsole="killall netconsole-host"
send_admin_command $kill_netconsole

# scp a bunch of files?

# start new code
log_info "launching new code..."

kill_robot=". /etc/profile.d/natinst-path.sh; /usr/local/frc/bin/frcKillRobot.sh -t -r;"
send_command $kill_robot


log_info "excelsior!"
